### ISSUE TITLE
Not working with array cache driver.

### ISSUE THREAD

**Issue by xSINIQx** [highideas/laravel-users-online#12]
As the title says, It worked perfect, but as soon as i change to array as my driver cache (which i need for a GeoIP package i'm using) it doesn't work anymore.

i wish i could be more informative but It doesn't throw any errors, on page or in the logs.
Some assistance would be great 👍

**Comment by GabrielDeveloper** [comment]
@xSINIQx I'll try to simulate but the issue can be that on array driver don't retained the values between requests:

http://laravel-recipes.com/recipes/97/setting-up-the-array-cache-driver

Are you using the GeoIP driver, right?

**Comment by xSINIQx** [comment]
yes, that's working correctly, i'm using [Laravel GeoIP](http://lyften.com/projects/laravel-geoip).. if i disable all parts of it and switch back to the default file cache driver everythig works just fine.

**Comment by GabrielDeveloper** [comment]
Yes, due to the fact this package use cache to storage all users online.

Thanks to use this package, and feel free to send PRs ! =)
