### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by HDVinnie** [highideas/laravel-users-online#22]
Just throwing these out there.

Counts
Count the number of active guests? (at login, register)(not signed in?)
Count the number of active users?

Sorting Methods
Option to sort the active users by username or mostRecent/leastRecent?

**Comment by GabrielDeveloper** [comment]
We implements the sort methods and it's available on last version: 2.2.x

About counts, using the laravel's method `count()` you can get the number of users actives `$users->allOnline()->count();`

Thanks by your suggestions!

**Comment by GabrielDeveloper** [comment]
Sorting Methods was done on last version!

Thanks!
