### ISSUE TITLE
undefined property

### ISSUE THREAD

**Issue by muzamilindra** [highideas/laravel-users-online#26]
im getting error like
"ErrorException in UsersOnlineTrait.php line 13: Undefined property: Illuminate\Database\Eloquent\Collection::$filter (View: C:\xampp\htdocs\e-access\laravel\resources\views\dashboard\dashboard.blade.php)" 

and

"ErrorException in UsersOnlineTrait.php line 13: Undefined property: Illuminate\Database\Eloquent\Collection::$filter"

i follow step by step..., but still getting error....

can any help me?
Im Using Laravel 5.3

**Comment by GabrielDeveloper** [comment]
What version are you using of this package? 2.2?

**Comment by muzamilindra** [comment]
yes im using 2.2 version.... but ever i try using 2.0 but can not download package, package is access denied

**Comment by GWeinschutz-modus** [comment]
@muzamilindra the version 2.2 only works with Laravel 5.4 the first error that you described was related to it.
The second problem is because the method allOnline is available only at the version 2.2^

**Comment by gpweins** [comment]
@muzamilindra the version 2.2 only works with Laravel 5.4 the first error that you described was related to it.
The second problem is because the method allOnline is available only at the version 2.2^

**Comment by muzamilindra** [comment]
How i used this package in laravel 5.3...?

**Comment by gpweins** [comment]
You need to use version 2.0.0 but on this version the method allOnline is not available.
You could take a look on the README on https://github.com/highideas/laravel-users-online/tree/2.0.0

**Comment by muzamilindra** [comment]
i use version 2.0 but why this package not publish using php artisan vendor:publish
