### ISSUE TITLE
User Status

### ISSUE THREAD

**Issue by TartanLeGrand** [highideas/laravel-users-online#27]
Hello, I want to say that the package is great!

I would like to make an improvement to make a status system. My problem is that I would like to create a different trick than online / offline user. But more with online / offline / busy / absent user.

Thank you for your answers.

**Comment by GabrielDeveloper** [comment]
Thanks for your comment, but now the user status does not belong to the scope of this package.

Maybe we could make another package with these specifications.

Thank you!
