### ISSUE TITLE
Database query builder is not found (Illuminate\Database\Query\Builder::allOnline())

### ISSUE THREAD

**Issue by fendiseptiawan0709** [highideas/laravel-users-online#28]
I have installed this package in accordance with the instructions provided.
After all the installation process I do, then I try to show all the users who are online. Following the command that I use (I put on the web route).

```
use App\User;

Route::get('/online', function(){
    $user = new User;
    $user->allOnline();
});
```

However, when I try to execute the command, the results shown are not as expected. Here's the look of the web page.

> BadMethodCallException in Builder.php line 2450:
> Call to undefined method Illuminate\Database\Query\Builder::allOnline()

![screencapture-localhost-project_management-public-online-1500449473951](https://user-images.githubusercontent.com/16249274/28355614-f330e77e-6c8e-11e7-92e6-adf3d78174a8.png)

What caused the error? And how do I solve that problem ???
thanks.

Note.
I am using laravel version 5.3
I use this package version 2.0.0

**Comment by GabrielDeveloper** [comment]
@fendiseptiawan0709 

On this version the method allOnline is not available(mostRecentOnline and leastRecentOnline too).
You could take a look on the README on https://github.com/highideas/laravel-users-online/tree/2.0.0 to see how works on this version

Thanks

**Comment by fendiseptiawan0709** [comment]
Thank you @GabrielDeveloper.
Sorry, It's my fault not to read documentation on github before using it.
I think I have to upgrade to Laravel version 5.4 to get this feature.
Thank you very much...

**Comment by GabrielDeveloper** [comment]
No problem @fendiseptiawan0709 ! Enjoy our package!
