### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hassansaqib** [highideas/laravel-users-online#3]
Hi, I have followed all your guided steps but am sticking somewhere. I am checking the following path:

http://localhost/adspacepk/public/users-online

it is showing 0 online users. Although I have two online users. I have also tried Auth::user()->isOnline(), it is also returning false while the user is logged in. I will appreciate your help.. 

Best,
Hassan

**Comment by GabrielDeveloper** [comment]
@hassansaqib, your version of Laravel is 5.2?

**Comment by hassansaqib** [comment]
Yes, Laravel 5.2

**Comment by hassansaqib** [comment]
Hi, Can you guide me what changes are required to fix it?

**Comment by GabrielDeveloper** [comment]
@hassansaqib  Sure, are you using the native cache of Laravel? this package use the cache to save the online user. You can verify your cache.

**Comment by hassansaqib** [comment]
I am using native cache, I think because I didn't make any changes for it. My .env file have following settings for cache.

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

**Comment by gpweins** [comment]
@hassansaqib could you please check if this recent update solves your issue?

**Comment by hassansaqib** [comment]
Thank you @gpweins . You did a great job. My problem resolved...

**Comment by gpweins** [comment]
@hassansaqib, kudos to @GabrielDeveloper, he wrote the fix!
