### ISSUE TITLE
Problems other middleware

### ISSUE THREAD

**Issue by loooping** [highideas/laravel-users-online#31]
I have 2 problem's

1 - I can't logout other middleware (ex: admin)
```
all to a member function pullCache() on null
/mypath/vendor/highideas/laravel-users-online/src/Listeners/LogoutListener.php#29
```
2 - How to exclude other middleware logged of method allOnline()?

You can help me?
Thanks broo

**Comment by GabrielDeveloper** [comment]
I didn't understand your doubt. Are you trying use other middlewares, so it's breaking?

**Comment by Roduan-kareem-aldeen** [comment]
about your first problem you need to : 
- modify Handel function in the LogoutListener.php file (check if $event->user is instance of Admin class and if $event->user is set and is not null) if yes then pullCache()

note : this solution works in case your multiAuth system is from two different model.

**Comment by GabrielDeveloper** [comment]
@loooping was added a validation on "LogoutListener" at the last version.

Thanks @RoduanKareemAldeen.
