### ISSUE TITLE
Logout seems not working.

### ISSUE THREAD

**Issue by bhaumikpandhi** [highideas/laravel-users-online#49]
Hello, I've setup of Laravel 5.4, and I'm using Laravel in-build auth system `php artisan make:auth`.

It seems there is a problem with logout, a user is not removing from online users list, even if I logout specific user.

**Comment by GabrielDeveloper** [comment]
What type of cache is setted?

**Comment by badianboss** [comment]
good morining dear great developer , i got  a litle problem the laravel-users-online package , i installed it's working , but it's showing in front of my online user the number '1' , i don't know where it's coming from . i want to showning 'online' instead '1'. if you can help me to solve to this solve that problem please  .see in the image clearly. thank you in advance .

![user_online](https://user-images.githubusercontent.com/35532731/35742865-c0379a98-0833-11e8-885f-5b00d74e9d14.PNG)

**Comment by GabrielDeveloper** [comment]
@badianboss are you using the method isOnline()? if yes, this method returns a boolean, you must verify this and translate to online or offline on your application.

**Comment by wongklirong** [comment]
Hello, I've setup of Laravel 5.5, and I'm using Laravel in-build auth system php artisan make:auth.

It seems there is a problem with logout, a user is not removing from online users list, even if I logout specific user. type of cache 7777

**Comment by nbrusquetti** [comment]
I have the same problem

Hello, I've setup of Laravel 5.4, and I'm using Laravel in-build auth system php artisan make:auth.

It seems there is a problem with logout, a user is not removing from online users list, even if I logout specific user.

**Comment by GabrielDeveloper** [comment]
The problems continue? Some changes was made, please update the package and let me know if the problem happen again.
