### ISSUE TITLE
allOnline not working

### ISSUE THREAD

**Issue by peterbayona** [highideas/laravel-users-online#50]
`$user->allOnline()`
it returns all users to me even though there are only two connected
I'm using laravel 5.5
`CACHE_DRIVER=file`
please if someone could give me a hand in this

**Comment by float1** [comment]
Hi,
for me it works on local development server (php artisan serve), but on production server it displays all users, strange for me. I use github for the project and pull the code...no errors from laravel framework

**Comment by GabrielDeveloper** [comment]
@peterbayona there are some problems because the cache file does not the correct permission.

Please verify if the cache file has the permission correct to read and write.

**Comment by GabrielDeveloper** [comment]
@float1 what type of cache is configured?
