### ISSUE TITLE
Call to a member function pullCache() on null

### ISSUE THREAD

**Issue by suthanbala** [highideas/laravel-users-online#53]
I am using the app in API mode. I've done everything as per the instructions. I am using the passport for authentication library. For the logout, I am running `Auth::logout();`. This is throwing the error `Call to a member function pullCache() on null`

**Comment by miadz** [comment]
and yes for me

**Comment by GabrielDeveloper** [comment]
@suthanbala sorry, but this package is not compatible with Passport yet.

I'm working to make compatible with Laravel Passport.

Thanks
