### ISSUE TITLE
last online

### ISSUE THREAD

**Issue by matro-skin** [highideas/laravel-users-online#57]
how  about to add field `lastonline` to `users` ?

**Comment by GabrielDeveloper** [comment]
@paulprok I didn't understand, tell me more about this field?

This package has a method that return the latest users online.

**Comment by paulprok** [comment]
How can I get know when the user was last time online?

**Comment by roncodes** [comment]
A bit late but you can easily get the last time the user was online like such

`$this->getCachedAt()`

I created an attribute on my user model like such

```
   /**
     * Get the time the user was last seen online
     */
    public function getLastOnlineAttribute() {
        return $this->getCachedAt();
    }
```
