### ISSUE TITLE
Laravel 5.8 Collision

### ISSUE THREAD

**Issue by HDVinnie** [highideas/laravel-users-online#67]
Hello,

I just wanted to make you aware that this is a issue with Laravel 5.8
https://github.com/highideas/laravel-users-online/blob/09b444fa6dc9818e07d23e2b2e87f9549ea4a62e/src/Listeners/LoginListener.php#L17

The default value is `120` which most keep the default and in session logic this amount to 120minutes. However, to conform with PSR-16 Laravel 5.8 changed the cache expiration time from minutes to seconds. So using this value as you do makes the user-online cache only last 120 seconds aka 2 minutes.

Just though I would let you know.

**Comment by GabrielDeveloper** [comment]
Thank @HDVinnie , I'll make the change to convert the session life config to seconds.

Or if you want, feels free to send PR.

**Comment by HDVinnie** [comment]
I guess you could just do `$event->user->setCache(config('session.lifetime') * 60); ` right?
