### ISSUE TITLE
Methods needs initialized object.

### ISSUE THREAD

**Issue by PitchRE** [highideas/laravel-users-online#73]
Hello.I'm curious why you need to initialize user object for these methods?

> $user = new User;
> $user->mostRecentOnline();
> $user->leastRecentOnline();

I would suggest making them static so you can run these like this ->

```
User::mostRecentOnline();
User::leastRecentOnline();
```

Cheers.

**Comment by GabrielDeveloper** [comment]
@PitchRE 

There is an endless discussion about whether static methods are a bad practice or not, so I preferred to create non-static methods because Laravel allows us to use Facades to achieve the same desired result.

I will update the documents to show how to use a static method through facades.
